### ISSUE TITLE
Chapter06 - withLoader TS2322

### ISSUE THREAD

**Issue by ITJarl1984** [PacktPublishing/Learn-React-with-TypeScript-3#1]
At the end of Chapter06, with all changes I am getting the following: 
TypeScript error in ./reactshop/src/withLoader.tsx(17,6):
Type '{}' is not assignable to type 'P'.
  '{}' is assignable to the constraint of type 'P', but 'P' could be instantiated with a different subtype of constraint 'object'.  TS2322

    15 |     </div>
    16 |   ) : (
  > 17 |     <Component {...props} />
       |      ^
    18 |   );
    19 | export default withLoader;

**Comment by carlrip** [comment]
Try using the following `withLoader` component:

```
const withLoader = <P extends object>(
  Component: React.ComponentType<P>
): React.FC<P & IProps> => (props: P & IProps) =>
  props.loading ? (
    <div className="loader-overlay">
      <div className="loader-circle-wrap">
        <div className="loader-circle" />
      </div>
    </div>
  ) : (
    <Component {...props} />
  );
```
